# 00. PyTorch fundamentals

Resource notebook:
    https://www.learnpytorch.io/00_pytorch_fundamentals/

### How to integrate your GPU with PyTorch and check if all is setup correctly

In [1]:
# Import pytorch library
import torch

In [2]:
# Check if GPU is available
torch.cuda.is_available()

True

In [3]:
# Check how many GPUs are available
torch.cuda.device_count()

1

In [4]:
# Check index of selected GPU
torch.cuda.current_device()

0

In [5]:
# Check index of selected GPU
torch.cuda.get_device_properties('cuda:0')

_CudaDeviceProperties(name='NVIDIA GeForce RTX 3080', major=8, minor=6, total_memory=10239MB, multi_processor_count=68)

In [6]:
# Get a name of GPU to check if it's right
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3080'

In [7]:
# Select GPU device if available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [8]:
# Create a tensor with random values 
sample_tensor = torch.rand(0, 10)
print('Sample tensor is on: ', sample_tensor.device)

Sample tensor is on:  cpu


In [9]:
# Moving tensor to the GPU
sample_tensor = sample_tensor.to(device)
print('Sample tensor is on: ', sample_tensor.device)

Sample tensor is on:  cuda:0


### Introduction to tensors 

In [10]:
# Importing most used libraries for data science and machine learning 
import torch
import numpy as np
import pandas as pd                                                                                                                                    
import matplotlib.pyplot as plt


#### About tensors

Documentation: https://pytorch.org/docs/stable/tensors.html

Additional resources for understanding tensors:

[1] https://towardsdatascience.com/better-visualizing-tensors-thanks-to-cities-b97e6b4ca2ca

[2] https://www.youtube.com/watch?v=f5liqUk0ZTw

[3] https://www.youtube.com/watch?v=bpG3gqDM80w

[4] https://www.youtube.com/watch?v=YxXyN2ifK8A (best one in my opinion)

Tensors are basically just a way to represent the data, and a tensor representation as matrixes and n-dim arrays is convenient way to do it. For example, if there's a tensor without any dimensions (ndim == 0) it means that's just a value a.k.a. "scalar". We can call it a "rank zero" tensor. Remember that matrixes are not tensors - it's just a way to represent them. In PyTorch it looks something like this:


In [11]:
# Creating a scalar
scalar = torch.tensor(5)

# Checking if the scalar has been created correctly.
print(scalar)

# Checking scalar's number of dimensions (should be equal to 0)
print(scalar.ndim)

# Getting tensor's value as a python int (only doable with scalars)
print(scalar.item())

tensor(5)
0
5


But if we need more than one value to determine one object, like a vector, that contains x,y,z coordinates, we need to use a list. For example:

In [12]:
# Creating a vector
vector = torch.tensor([4, 4, 6])

# Checking if the vector has been created correctly.
print(vector)

# Checking vector's number of dimensions.
print(vector.ndim)


tensor([4, 4, 6])
1


As we can see the dimension now equals to one. That's because we have one square bracket list at value initialization. But one dimensional vector isn't really useful.
In real case scenario, we would have a list of vectors. And a list of vectors is really a matrix.
For example:

In [13]:
# Creating a MATRIX
MATRIX = torch.tensor([[4, 4, 7],
                        [5, 5, 8],
                        [6, 6, 9],
                        [7, 7, 3]])

# Checking if the MATRIX has been created correctly.
print(MATRIX)

# Checking vector's number of dimensions. 
print(MATRIX.ndim)

tensor([[4, 4, 7],
        [5, 5, 8],
        [6, 6, 9],
        [7, 7, 3]])
2


But if we have a complicated structure that requires list of matrixes, it really means that we need store data in a 3-dimensional tensor. Real life example would be an image that has three channels: red, green, and blue. Each of the channels is a matrix that shows the intensity of each pixel in that channel. To describe the structure of the single image, we need each channel.

In [14]:
# Creating a 3D vector (rank 1 tensor in 3 dimensions)
TENSOR = torch.tensor([[[1, 2, 3],
                        [5, 6, 7],
                        [7, 8, 9]]])

# Checking if the vector has been created correctly. 
print(TENSOR)

# Checking vector's number of dimensions 
print(TENSOR.ndim)

# Checking a size of a tensor 
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [5, 6, 7],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


So tensors are really an organized data structure, and they have as many rows and columns as there are needed to describe one object or a whole model.

#### Random tensors

The way that machine learning models are trained is by using random tensors. It is because they start with tensors full of random numbers and then they adjust their values to better fit the data.

`Start with a random tensor -> look at the data -> adjust the values to better fit the data -> repeat the step 2 and 3 until you get right values`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html 

In [15]:
# Create random tensor 
random_tensor = torch.rand(3, 4)

# Show random tensor
print(random_tensor)

# Show random tensor shape
print(random_tensor.shape)

# Show random tensor ndim
print(random_tensor.ndim)

tensor([[0.1103, 0.0909, 0.5301, 0.0245],
        [0.3747, 0.0146, 0.9193, 0.4621],
        [0.3490, 0.2893, 0.9815, 0.7144]])
torch.Size([3, 4])
2


In [16]:
# Create a random tensor that is similar to an image tensor.
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

torch.Size([224, 224, 3])
3


#### Zeros and ones

In [18]:
# Create tensor of all zeros
zeros = torch.zeros(3, 4)
print(zeros)
print(zeros * random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [21]:
# Create tensor of all ones 
ones = torch.ones(3, 4)
print(ones)
print(ones.dtype) #default type for pytorch is torch.float32


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


#### Creating range of tensors and tensors-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(0, 10) # torch.arange(start=0, end=11, step=2)
print(one_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


If we have a tensor and we want to create another tensor that is the same shape as the original one, but filled with zeros/one, we can use zeros_like/ones/like method, like below:

In [25]:
# Creating tensor-like 
ten_zeros = torch.zeros_like(one_to_ten) # torch.ones_like(one_to_ten)
print(ten_zeros)


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
