# 00. PyTorch fundamentals

Resource notebook:
    https://www.learnpytorch.io/00_pytorch_fundamentals/

### How to integrate your GPU with PyTorch and check if all is setup correctly

In [23]:
# Import pytorch library
import torch

In [24]:
# Check if GPU is available
torch.cuda.is_available()

True

In [25]:
# Check how many GPUs are available
torch.cuda.device_count()

1

In [26]:
# Check index of selected GPU
torch.cuda.current_device()

0

In [27]:
# Check index of selected GPU
torch.cuda.get_device_properties('cuda:0')

_CudaDeviceProperties(name='NVIDIA GeForce RTX 3080', major=8, minor=6, total_memory=10239MB, multi_processor_count=68)

In [28]:
# Get a name of GPU to check if it's right
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3080'

In [29]:
# Select GPU device if available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [30]:
# Create a tensor with random values 
sample_tensor = torch.rand(0, 10)
print('Sample tensor is on: ', sample_tensor.device)

Sample tensor is on:  cpu


In [31]:
# Moving tensor to the GPU
sample_tensor = sample_tensor.to(device)
print('Sample tensor is on: ', sample_tensor.device)

Sample tensor is on:  cuda:0


### Introduction to tensors 

In [32]:
# Importing most used libraries for data science and machine learning 
import torch
import numpy as np
import pandas as pd                                                                                                                                    
import matplotlib.pyplot as plt


#### About tensors

Documentation: https://pytorch.org/docs/stable/tensors.html

Additional resources for understanding tensors:

[1] https://towardsdatascience.com/better-visualizing-tensors-thanks-to-cities-b97e6b4ca2ca

[2] https://www.youtube.com/watch?v=f5liqUk0ZTw

[3] https://www.youtube.com/watch?v=bpG3gqDM80w

[4] https://www.youtube.com/watch?v=YxXyN2ifK8A (best one in my opinion)

Tensors are basically just a way to represent the data, and a tensor representation as matrixes and n-dim arrays is convenient way to do it. For example, if there's a tensor without any dimensions (ndim == 0) it means that's just a value a.k.a. "scalar". We can call it a "rank zero" tensor. Remember that matrixes are not tensors - it's just a way to represent them. In PyTorch it looks something like this:


In [33]:
# Creating a scalar
scalar = torch.tensor(5)

# Checking if the scalar has been created correctly.
print(scalar)

# Checking scalar's number of dimensions (should be equal to 0)
print(scalar.ndim)

# Getting tensor's value as a python int (only doable with scalars)
print(scalar.item())

tensor(5)
0
5


But if we need more than one value to determine one object, like a vector, that contains x,y,z coordinates, we need to use a list. For example:

In [34]:
# Creating a vector
vector = torch.tensor([4, 4, 6])

# Checking if the vector has been created correctly.
print(vector)

# Checking vector's number of dimensions.
print(vector.ndim)


tensor([4, 4, 6])
1


As we can see the dimension now equals to one. That's because we have one square bracket list at value initialization. But one dimensional vector isn't really useful.
In real case scenario, we would have a list of vectors. And a list of vectors is really a matrix.
For example:

In [35]:
# Creating a MATRIX
MATRIX = torch.tensor([[4, 4, 7],
                        [5, 5, 8],
                        [6, 6, 9],
                        [7, 7, 3]])

# Checking if the MATRIX has been created correctly.
print(MATRIX)

# Checking vector's number of dimensions. 
print(MATRIX.ndim)

tensor([[4, 4, 7],
        [5, 5, 8],
        [6, 6, 9],
        [7, 7, 3]])
2


But if we have a complicated structure that requires list of matrixes, it really means that we need store data in a 3-dimensional tensor. Real life example would be an image that has three channels: red, green, and blue. Each of the channels is a matrix that shows the intensity of each pixel in that channel. To describe the structure of the single image, we need each channel.

In [36]:
# Creating a 3D vector (rank 1 tensor in 3 dimensions)
TENSOR = torch.tensor([[[1, 2, 3],
                        [5, 6, 7],
                        [7, 8, 9]]])

# Checking if the vector has been created correctly. 
print(TENSOR)

# Checking vector's number of dimensions 
print(TENSOR.ndim)

# Checking a size of a tensor 
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [5, 6, 7],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


So tensors are really an organized data structure, and they have as many rows and columns as there are needed to describe one object or a whole model.

#### Random tensors

The way that machine learning models are trained is by using random tensors. It is because they start with tensors full of random numbers and then they adjust their values to better fit the data.

`Start with a random tensor -> look at the data -> adjust the values to better fit the data -> repeat the step 2 and 3 until you get right values`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html 

In [37]:
# Create random tensor 
random_tensor = torch.rand(3, 4)

# Show random tensor
print(random_tensor)

# Show random tensor shape
print(random_tensor.shape)

# Show random tensor ndim
print(random_tensor.ndim)

tensor([[0.2821, 0.4957, 0.4892, 0.8279],
        [0.0867, 0.8728, 0.8622, 0.7512],
        [0.1039, 0.8838, 0.7903, 0.7171]])
torch.Size([3, 4])
2


In [38]:
# Create a random tensor that is similar to an image tensor.
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

torch.Size([224, 224, 3])
3


#### Zeros and ones

In [39]:
# Create tensor of all zeros
zeros = torch.zeros(3, 4)
print(zeros)
print(zeros * random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [40]:
# Create tensor of all ones 
ones = torch.ones(3, 4)
print(ones)
print(ones.dtype) #default type for pytorch is torch.float32


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


#### Creating range of tensors and tensors-like

In [41]:
# Use torch.arange()
one_to_ten = torch.arange(0, 10) # torch.arange(start=0, end=11, step=2)
print(one_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


If we have a tensor and we want to create another tensor that is the same shape as the original one, but filled with zeros/one, we can use zeros_like/ones/like method, like below:

In [42]:
# Creating tensor-like 
ten_zeros = torch.zeros_like(one_to_ten) # torch.ones_like(one_to_ten)
print(ten_zeros)


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


#### Tensor datatypes

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

**Note:** Wrong tensor datatype is one of three most common errors anyone can run into with PyTorch and Deep Learning. All most common errors are listed below:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

PyTorch's default datatype is torch.float32 as shown below:

In [43]:
# Float 32 tensor
f32_tensor = torch.tensor([3.0, 7.0, 5.0],
                           dtype=None, # What datatype is the tensor. All listed on https://pytorch.org/docs/stable/tensors.html
                           device=None, # What device is your tensor on. By default the device is 'cpu'.
                           requires_grad=False) # Whether or not to track the gradient of the tensor wih its operations.
print(f32_tensor)
print(f32_tensor.dtype)

tensor([3., 7., 5.])
torch.float32


But we can change it:

In [44]:
# Float 64 tensor
f64_tensor = torch.tensor([3.0, 7.0, 5.0],
                           dtype=torch.float64, 
                           device=None, 
                           requires_grad=False) 

print(f64_tensor)
print(f64_tensor.dtype)

tensor([3., 7., 5.], dtype=torch.float64)
torch.float64


PyTorch can manage to operate on tensors with different datatypes, as shown below:

In [45]:
print(f32_tensor * f64_tensor)

tensor([ 9., 49., 25.], dtype=torch.float64)


But sometimes it is not so obvious.

#### Getting information from tensors

1. Tensors not right datatype - to get datatype of tensors, use: `tensor.dtype`
2. Tensors not right shape - to get shape of tensors, use: `tensor.shape`
3. Tensors not on right device - to get device of tensors, use: `tensor.device`

Example:

In [46]:
# Crete a tensor
TENSOR = torch.rand(3, 4)

# Show the tensor
print(TENSOR)

# Get a datatype of the tensor
print(f'Datatype of the tensor: {TENSOR.dtype}')

# Get the shape of the tensor
print(f'Shape of the tensor: {TENSOR.shape}') # Can use .size() to get the size of the tensor. One is a method and one is a attribute.

# Get the device of the tensor
print(f'Device on which the tensor is on: {TENSOR.device}')

tensor([[0.2662, 0.4129, 0.1507, 0.8818],
        [0.9928, 0.4468, 0.2544, 0.7183],
        [0.9988, 0.3611, 0.0520, 0.6360]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device on which the tensor is on: cpu


#### Manipulating tensors - tensor operations

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise multiplication)
* Division
* Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** of the two tensors must match:
   * `(3, 2) @ (3, 2)` -> won't work
   * `(2, 3) @ (3, 2)` -> will work
   * `(3, 2) @ (2, 3)` -> will work
2. The resulting matrix has the shape of the **outer dimensions**:
   * `(2, 3) @ (3, 2)` -> `(2, 2)`
   * `(3, 2) @ (2, 3)` -> `(3, 3)`


In [47]:
""" How to add a value to a tensor """
# Create a tensor 
tensor = torch.tensor([1, 2, 3])

# Addition
print(tensor + 10)

# Alternatively we can use torch.add()
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [48]:
""" How to subtract a value from a tensor """
# Create a tensor 
tensor = torch.tensor([1, 2, 3])

# Subtraction
print(tensor - 10)

# Alternatively we can use torch.sub()
print(torch.sub(tensor, 10))

tensor([-9, -8, -7])
tensor([-9, -8, -7])


In [49]:
""" How to multiply a tensor by a scalar """
# Create a tensor 
tensor = torch.tensor([1, 2, 3])

# Multiplication
print(tensor * 10)

# Alternatively we can use torch.mul()
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [50]:
""" How to divide a tensor by a scalar """
# Create a tensor 
tensor = torch.tensor([1, 2, 3])

# Multiplication
print(tensor / 10)

# Alternatively we can use torch.div()
print(torch.div(tensor, 10))

tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])


#### Matrix multiplication

Two ways of performing multiplication in ML&DL:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More on Matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html



In [51]:
# Create a tensor 
tensor = torch.tensor([1, 2, 3])

# Element wise multiplication
print(f'{tensor} * {tensor}\nEquals to: {tensor * tensor}')


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals to: tensor([1, 4, 9])


Matrix multiplication can be done by hand or by using torch.matmul() function:

In [52]:
# Matrix multiplication by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print('By hand: ', value)

# Matrix multiplication with torch.matmul() function
print('Matmul function: ', torch.matmul(tensor, tensor))

By hand:  tensor(14)
Matmul function:  tensor(14)


But we need to bare in mind that PyTorch has been created to be efficient in its calculation. Therefore using torch.matmal() function is ten times faster than using loops.

#### Most common error in Deep Learning: shape error

Previous example was rather simple, therefore we didn't get any error. 

Let's break the first rule of matrix multiplication -

"1. The **inner dimensions** of the two tensors must match:
   * `(3, 2) @ (3, 2)` -> won't work
   * `(2, 3) @ (3, 2)` -> will work
   * `(3, 2) @ (2, 3)` -> will work"

, and find out what happens:

In [53]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

print(torch.mm(tensor_A, tensor_B)) # torch.mm is an alias for torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix this issue, we can multiply the shape of one of our tensors using **transpose**.

**Transpose** - an operation that switches axes or dimensions of a given tensor.

In [ ]:
# Original tensor
print(tensor_B)

# Transposed tensor
print(tensor_B.T)

# Multiplication
print(torch.mm(tensor_A, tensor_B.T))

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


Here's step by step what happened:

In [ ]:
print('1. We get original tensors')
print(f' - Original shape of tensor_A: {tensor_A.shape}')
print(f' - Original shape of tensor_B: {tensor_B.shape}')
print("2. We transpose the tensor_A or tensor_B. It's your choice.")
print(f' - New shape of new transposed tensor_B: {tensor_B.T.shape}')
print('3. As the inner dimensions of tensor_A and tensor_B are the same, we can multiply them together.')
output = torch.mm(tensor_A, tensor_B.T)
print(f'Output: {output}')
print(f'4. The result matrix has the same dimensions as outer dimensions of tensor_A and tensor_B, which are 3 and 3')
print(f' - Shape of result matrix: {output.shape}')

1. We get original tensors
 - Original shape of tensor_A: torch.Size([3, 2])
 - Original shape of tensor_B: torch.Size([3, 2])
2. We transpose the tensor_A or tensor_B. It's your choice.
 - New shape of new transposed tensor_B: torch.Size([2, 3])
3. As the inner dimensions of tensor_A and tensor_B are the same, we can multiply them together.
Output: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
4. The result matrix has the same dimensions as outer dimensions of tensor_A and tensor_B, which are 3 and 3
 - Shape of result matrix: torch.Size([3, 3])


#### Examples of the second rule of matrix multiplication

"2. The resulting matrix has the shape of the **outer dimensions**:
   * `(2, 3) @ (3, 2)` -> `(2, 2)`
   * `(3, 2) @ (2, 3)` -> `(3, 3)`"

In [ ]:
# (3, 2) @ (2, 3) -> (3, 3)
print(torch.matmul(torch.rand(3,2), torch.rand(2,3)))

# (2, 3) @ (3, 2) -> (2, 2)
print(torch.matmul(torch.rand(2,3), torch.rand(3,2)))

# (3, 10) @ (10, 3) -> (3, 3)
print(torch.matmul(torch.rand(3,10), torch.rand(10,3)))

# (3, 10) @ (10, 5) -> (3, 5)
print(torch.matmul(torch.rand(3,10), torch.rand(10,5)))


tensor([[0.5236, 0.2829, 0.5608],
        [0.3272, 0.5757, 0.3321],
        [0.2349, 0.1500, 0.2505]])
tensor([[0.9166, 0.9019],
        [0.9706, 0.9475]])
tensor([[3.7839, 2.6333, 3.7173],
        [2.2040, 1.8659, 2.5815],
        [3.3008, 2.1486, 3.6346]])
tensor([[3.5925, 3.3448, 3.3426, 3.2264, 2.5871],
        [3.1340, 3.6557, 2.9148, 3.5357, 2.3806],
        [2.6682, 2.5946, 2.6844, 2.3902, 1.8340]])


#### Finding the min, max, mean, sum etc. (tensor aggregation)

In [ ]:
""" Finding minimal value in the tensor """
# Create a tensor
x = torch.arange(0, 100, 10)

# Show the tensor
print(x)

# Find the minimal value in tensor
print(torch.min(x))

# Alternative way to find minimum value in tensor
print(x.min())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(0)


In [ ]:
""" Finding maximum value in the tensor """
# Create a tensor
x = torch.arange(0, 100, 10)

# Show the tensor
print(x)

# Find maximum value in tensor
print(torch.max(x))

# Alternative way to find maximum value in tensor
print(x.max())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(90)
tensor(90)


In [ ]:
""" Finding average value in the tensor """
# Create a tensor
x = torch.arange(0, 100, 10, dtype=torch.float32)

# Show the tensor
print(x)

# Find mean value in tensor - note: torch.mean() function requires a torch.float32 dtype
print(torch.mean(x))

# Alternative way to find mean value in tensor
print(x.mean())

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
tensor(45.)
tensor(45.)


In [ ]:
""" Finding a sum of the tensor """
# Create a tensor
x = torch.arange(0, 100, 10)

# Show the tensor
print(x)

# Find a sum of the tensor
print(torch.sum(x))

# Alternative way to find a sum of the tensor
print(x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(450)
tensor(450)


In [ ]:
""" Finding a position (index) of min in the tensor """
# Create a tensor
x = torch.arange(1, 100, 10)

# Show the tensor
print(x)

# Find a position (index) of min in the tensor
print(torch.argmin(x))

# Alternative way to find a position (index) of min in the tensor
print(x.argmin())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(0)
tensor(0)


In [ ]:
""" Finding a position (index) of max in the tensor """
# Create a tensor
x = torch.arange(1, 100, 10)

# Show the tensor
print(x)

# Find a position (index) of max in the tensor
print(torch.argmax(x))

# Alternative way to find a position (index) of max in the tensor
print(x.argmax())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(9)
tensor(9)


#### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in certain way


In [ ]:
# Create a tensor
x = torch.arange(1., 10.)
print(x, x.shape)

# Add a new dimension
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [ ]:
# Change the view
z = x.view(1, 9)
print(z, z.shape)

# Changing z changes x because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
print(z, x)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x]) # dim = 1
print(x_stacked)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [ ]:
# torch.squeeze() removes all 1 dimensions
print(x_reshaped, x_reshaped.shape)
print(x_reshaped.squeeze(), x_reshaped.squeeze().shape)


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [ ]:
# torch.unsqueeze() adds 1 dimensions
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
print(x_squeezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(0)
print(x_unsqueezed)
print(x_unsqueezed.shape)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of target tensor in a specified order
x = torch.randn(2, 3, 5)
print(x.shape)
x_permuted = torch.permute(x, (2, 0, 1))
print(x_permuted.shape)


torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


#### Indexing

Indexing in PyTorch is similar to indexing with NumPy arrays.


In [ ]:
# Create tensor 
import torch

x = torch.arange(1,10).reshape(1, 3 ,3)
print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [ ]:
#Let's index on our new tensor
print(x[0, 0, 1]) #change '0' in square brackets and see what happens

In [ ]:
# You can use ":" to select all of target dimension
print(x[:, :, 0])

tensor([[1, 4, 7]])


#### PyTorch tensors and NumPy

NumPy is very popular scientific Python numerical computing library. s
And because of it, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # When converting from numpy array to torch tensor default dtype is float64
print(array, tensor)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor, numpy_tensor)
tensor = tensor + 1
print(tensor, numpy_tensor) # They don't share memory


tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.]) [1. 1. 1. 1. 1. 1. 1.]


#### Reproducibility (Creating seed)

Extra resources:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [ ]:
import torch

RANDOM_SEED = 2137
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

tensor([[0.7206, 0.2809, 0.1826, 0.1297],
        [0.4757, 0.5004, 0.3709, 0.4002],
        [0.2189, 0.3464, 0.8074, 0.8887]])
tensor([[0.1233, 0.4134, 0.1043, 0.1843],
        [0.0656, 0.3246, 0.3044, 0.7056],
        [0.0455, 0.3311, 0.9790, 0.9308]])


#### Putting tensors (and models) on the GPU

In [54]:
# Create tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU
tensor_gpu = tensor.to(device)
print(tensor_gpu, tensor_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0
